### Homework

In [1]:
import pandas as pd
import numpy as np

interesting_columns = [
    'latitude',
    'longitude',
    'housing_median_age',
    'total_rooms',
    'total_bedrooms',
    'population',
    'households',
    'median_income',
    'median_house_value',
    'ocean_proximity',
]

df = pd.read_csv('housing.csv')
df = df[interesting_columns].fillna(0)
df['rooms_per_household'] = df.total_rooms/df.households
df['bedrooms_per_room'] = df.total_bedrooms/df.total_rooms
df['population_per_household'] = df.population/df.households
df.head().T

                                 0         1         2         3         4
latitude                     37.88     37.86     37.85     37.85     37.85
longitude                  -122.23   -122.22   -122.24   -122.25   -122.25
housing_median_age            41.0      21.0      52.0      52.0      52.0
total_rooms                  880.0    7099.0    1467.0    1274.0    1627.0
total_bedrooms               129.0    1106.0     190.0     235.0     280.0
population                   322.0    2401.0     496.0     558.0     565.0
households                   126.0    1138.0     177.0     219.0     259.0
median_income               8.3252    8.3014    7.2574    5.6431    3.8462
median_house_value        452600.0  358500.0  352100.0  341300.0  342200.0
ocean_proximity           NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY
rooms_per_household       6.984127  6.238137  8.288136  5.817352  6.281853
bedrooms_per_room         0.146591  0.155797  0.129516  0.184458  0.172096
population_per_household  2.555556  2.109842   2.80226  2.547945  2.181467

#### Q1: What is the most frequent observation (mode) for the column ocean_proximity?

In [2]:
df.ocean_proximity.mode()

0    <1H OCEAN
Name: ocean_proximity, dtype: object

#### Q2: Create the correlation matrix and find the two features with the biggest correlation?

In [3]:
from IPython.display import display
numerical = df.columns[df.dtypes != 'object'].to_list()
corr_M = pd.DataFrame(index=numerical, columns=numerical)
for column_a in numerical:
    for column_b in numerical:
        corr_M.loc[column_a, column_b] = df[column_a].corr(df[column_b])
        


display(corr_M)

,latitude,longitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,rooms_per_household,bedrooms_per_room,population_per_household
latitude,1.0,-0.924664,0.011173,-0.0361,-0.065318,-0.108785,-0.071035,-0.079809,-0.14416,0.106389,-0.104112,0.002366
longitude,-0.924664,1.0,-0.108197,0.044568,0.068082,0.099773,0.05531,-0.015176,-0.045967,-0.02754,0.084836,0.002476
housing_median_age,0.011173,-0.108197,1.0,-0.361262,-0.317063,-0.296244,-0.302916,-0.119034,0.105623,-0.153277,0.125396,0.013191
total_rooms,-0.0361,0.044568,-0.361262,1.0,0.920196,0.857126,0.918484,0.19805,0.134153,0.133798,-0.174583,-0.024581
total_bedrooms,-0.065318,0.068082,-0.317063,0.920196,1.0,0.866266,0.966507,-0.007295,0.049148,0.002717,0.122205,-0.028019
population,-0.108785,0.099773,-0.296244,0.857126,0.866266,1.0,0.907222,0.004834,-0.02465,-0.072213,0.031397,0.069863
households,-0.071035,0.05531,-0.302916,0.918484,0.966507,0.907222,1.0,0.013033,0.065843,-0.080598,0.059818,-0.027309
median_income,-0.079809,-0.015176,-0.119034,0.19805,-0.007295,0.004834,0.013033,1.0,0.688075,0.326895,-0.573836,0.018766
median_house_value,-0.14416,-0.045967,0.105623,0.134153,0.049148,-0.02465,0.065843,0.688075,1.0,0.151948,-0.238759,-0.023737
rooms_per_household,0.106389,-0.02754,-0.153277,0.133798,0.002717,-0.072213,-0.080598,0.326895,0.151948,1.0,-0.387465,-0.004852
bedrooms_per_room,-0.104112,0.084836,0.125396,-0.174583,0.122205,0.031397,0.059818,-0.573836,-0.238759,-0.387465,1.0,0.003047
population_per_household,0.002366,0.002476,0.013191,-0.024581,-0.028019,0.069863,-0.027309,0.018766,-0.023737,-0.004852,0.003047,1.0

In [4]:
max_correlation = 0
correlated_ones = None
for i in range(len(numerical)):
    for j in range(i+1, len(numerical)):
        if corr_M.loc[numerical[i], numerical[j]] > max_correlation:
            max_correlation = corr_M.loc[numerical[i], numerical[j]]
            correlated_ones = (numerical[i], numerical[j])
print(max_correlation, correlated_ones)

0.966507240042039 ('total_bedrooms', 'households')

#### Make median_house_value binary

In [5]:
m = df.median_house_value.mean()
df['above_average'] = (df['median_house_value'] > m).astype(int)

In [6]:

from sklearn.model_selection import train_test_split

np.random.seed(42)

df_full_train, df_test = train_test_split(df, test_size=0.2)

df_train, df_val = train_test_split(df_full_train, test_size=0.25)

y_test = df_test.above_average.to_numpy()
yp_test = df_test.median_house_value.to_numpy()
del df_test['above_average']
del df_test['median_house_value']

y_val = df_val.above_average.to_numpy()
yp_val = df_val.median_house_value.to_numpy()
del df_val['above_average']
del df_val['median_house_value']

y_train = df_train.above_average.to_numpy()
yp_train = df_train.median_house_value.to_numpy()
del df_train['above_average']
del df_train['median_house_value']

#### Q3: Mutual information

In [7]:
from sklearn.metrics import mutual_info_score
mi_score = mutual_info_score(df['ocean_proximity'], df['above_average'])
np.round(mi_score, decimals=2)

0.1

#### Q4: Train logistic regression

In [8]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [9]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train.to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val.to_dict(orient='records')
X_val = dv.transform(val_dict)

In [10]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [11]:
y_pred = model.predict(X_val)
global_accuracy = (y_pred == y_val).mean()
np.round(global_accuracy, decimals=2)

0.84

#### Q5: find the least useful feature using the feature elimination technique.

In [12]:

q5_columns = ['total_rooms', 'total_bedrooms', 'population', 'households']


dv = DictVectorizer(sparse=False)

train_dict = df_train[q5_columns].to_dict(orient='records')
_X_train = dv.fit_transform(train_dict)

val_dict = df_val[q5_columns].to_dict(orient='records')
_X_val = dv.transform(val_dict)

model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
model.fit(_X_train, y_train)

y_pred = model.predict(_X_val)
_accuracy = (y_pred == y_val).mean()


less_important_feature = None
best_diff = 1
for column in q5_columns:
    dv = DictVectorizer(sparse=False)

    train_dict = df_train[q5_columns].drop(labels=column, axis=1).to_dict(orient='records')
    _X_train = dv.fit_transform(train_dict)

    val_dict = df_val[q5_columns].drop(labels=column, axis=1).to_dict(orient='records')
    _X_val = dv.transform(val_dict)

    model = LogisticRegression(solver="liblinear", C=1.0, max_iter=1000, random_state=42)
    model.fit(_X_train, y_train)

    y_pred = model.predict(_X_val)
    current_accuracy = (y_pred == y_val).mean()
    if np.abs(current_accuracy-_accuracy) < best_diff:
        best_diff = np.abs(current_accuracy-_accuracy)
        less_important_feature = column
display(less_important_feature, best_diff)

'households'

0.02761627906976749

#### Q6: Linear regression

In [13]:
df.head().T

                                 0         1         2         3         4
latitude                     37.88     37.86     37.85     37.85     37.85
longitude                  -122.23   -122.22   -122.24   -122.25   -122.25
housing_median_age            41.0      21.0      52.0      52.0      52.0
total_rooms                  880.0    7099.0    1467.0    1274.0    1627.0
total_bedrooms               129.0    1106.0     190.0     235.0     280.0
population                   322.0    2401.0     496.0     558.0     565.0
households                   126.0    1138.0     177.0     219.0     259.0
median_income               8.3252    8.3014    7.2574    5.6431    3.8462
median_house_value        452600.0  358500.0  352100.0  341300.0  342200.0
ocean_proximity           NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY  NEAR BAY
rooms_per_household       6.984127  6.238137  8.288136  5.817352  6.281853
bedrooms_per_room         0.146591  0.155797  0.129516  0.184458  0.172096
population_per_household  2.555556  2.109842   2.80226  2.547945  2.181467
above_average                    1         1         1         1         1

In [14]:
from sklearn.linear_model import Ridge

y_log = np.log1p(yp_train)

def rmse(y_pred, y_ref):
    error = y_pred - y_ref
    mse = error**2
    return np.sqrt(mse.mean())

for a in [0, 0.01, 0.1, 1, 10]:
    model = Ridge(alpha=a, solver="sag", random_state=42)
    

    dv = DictVectorizer(sparse=False)

    train_dict = df_train.to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)

    val_dict = df_val.to_dict(orient='records')
    X_val = dv.transform(val_dict)

    model.fit(X_train, y_log)
    yp_pred = model.predict(X_val)
    print(a, np.round(rmse(yp_pred, np.log1p(yp_val)), decimals=3))

0 0.526
0.01 0.526
0.1 0.526
1 0.526
10 0.526